### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by diego-betto** [zxbodya/yii2-image-attachment#10]
Hi, 
how can i handle multiple images upload? It's possible?

Thank you!

**Comment by zxbodya** [comment]
Do you want to create gallery?  

This may be useful:
https://github.com/zxbodya/yii2-gallery-manager

**Comment by diego-betto** [comment]
Oh, nice ext!
But I just need to allow users to upload max 3 pics per post

**Comment by zxbodya** [comment]
You can define 3 image attachement behaviours in you model (eg. image1, 2, 3), but it sounds rather strange...

---

Gallery manager ext was originally desgned for admin site section, so it has not limitation on image count... And if you are doing admin site section - consider using it, and just put a note somewhere that only first 3 imagaes would be used.
 
If you need it - you can do that by extending gallery extension to limit max number of images allowed, it should not be that hard(literally one check server side, and one client side + additional configuration parameter in behavior configuration).

**Comment by diego-betto** [comment]
Thank you! I'll try! :)
