### ISSUE TITLE
TimestampBehavior::className()

### ISSUE THREAD

**Issue by smartbit45** [zxbodya/yii2-image-attachment#15]
Здравствуйте! Какую функцию выполняет статический метод кроме установки метки времени?

`public function behaviors()
{
    return [
        TimestampBehavior::className(),
        'coverBehavior' => [
...`

Насколько я понимаю, в базе данных должны существовать поля created_at и updated_at для его работы. Могу ли я убрать этот метод из public function behaviors() без последствий для работы расширения?

**Comment by zxbodya** [comment]
yes, it should not be required for extension to work

**Comment by zxbodya** [comment]
updated the readme, removing this from example
