### ISSUE TITLE
Call to a member function hasImage() on null

### ISSUE THREAD

**Issue by mmbprog** [zxbodya/yii2-image-attachment#6]
in create new model i have this problem ...

```PHP
echo ImageAttachmentWidget::widget(
	[
	    'model' => $model,
	    'behaviorName' => 'coverBehavior',
	    'apiRoute' => 'news/imgAttachApi',
	]);
```

**Comment by zxbodya** [comment]
Looks like it happens not because your model is new, but because it has no behaviour named "coverBehavior" or it just fails to find it... 

Can you post your model code?

**Comment by mmbprog** [comment]
here you are ...

<?php

namespace backend\controllers;

use Yii;
use backend\models\News;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\behaviors\TimestampBehavior;

use zxbodya\yii2\galleryManager\GalleryManager;
use zxbodya\yii2\galleryManager\GalleryManagerAction;
use zxbodya\yii2\galleryManager\GalleryBehavior;
use zxbodya\yii2\imageAttachment\ImageAttachmentBehavior;
use zxbodya\yii2\imageAttachment\ImageAttachmentAction;


/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    public function behaviors()
    {        
        return [
            TimestampBehavior::className(),
            'coverBehavior' => [
                'class' => ImageAttachmentBehavior::className(),
                // type name for model
                'type' => 'news',
                // image dimmentions for preview in widget 
                'previewHeight' => 200,
                'previewWidth' => 300,
                // extension for images saving
                'extension' => 'jpg',
                // path to location where to save images
                'directory' => Yii::getAlias('@webroot') . 'media/images/news/cover',
                'url' => Yii::getAlias('@web') . 'media/images/news/cover',
                // additional image versions
                'versions' => [
                    'small' => function ($img) {
                        /** @var ImageInterface $img */
                        return $img
                            ->copy()
                            ->resize($img->getSize()->widen(200));
                    },
                    'medium' => function ($img) {
                        /** @var ImageInterface $img */
                        $dstSize = $img->getSize();
                        $maxWidth = 800;
                        if ($dstSize->getWidth() > $maxWidth) {
                            $dstSize = $dstSize->widen($maxWidth);
                        }
                        return $img
                            ->copy()
                            ->resize($dstSize);
                    },
                ]
            ],
            'galleryBehavior' => [
                'class' => GalleryBehavior::className(),
                'type' => 'news',
                'extension' => 'jpg',
                'directory' => Yii::getAlias('@webroot') . 'media/images/news/gallery',
                'url' => Yii::getAlias('@web') . 'media/images/news/gallery',
                'tableName' => 'news_newsgallery',
                'versions' => [
                    'small' => function ($img) {
                        /** @var \Imagine\Image\ImageInterface $img */
                        return $img
                            ->copy()
                            ->thumbnail(new \Imagine\Image\Box(200, 200));
                    },
                    'medium' => function ($img) {
                         /** @var Imagine\Image\ImageInterface $img */
                        $dstSize = $img->getSize();
                        $maxWidth = 800;
                        if ($dstSize->getWidth() > $maxWidth) {
                            $dstSize = $dstSize->widen($maxWidth);
                        }
                        return $img
                            ->copy()
                            ->resize($dstSize);
                    },
                ]
            ]
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => News::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'galleryApi' => [
                'class' => GalleryManagerAction::className(),
               // mappings between type names and model classes (should be the same as in behaviour)
               'types' => [
                    'news' => News::className()
                ]
            ],
            'imgAttachApi' => [
                'class' => ImageAttachmentAction::className(),
                // mappings between type names and model classes (should be the same as in behaviour)
                'types' => [
                    'news' => News::className()
                ]
            ],
        ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new News();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

**Comment by zxbodya** [comment]
Ouch... This `behaviors` method should be in model (class `News`), not in controller(`NewsController`).

**Comment by mmbprog** [comment]
thx ... but what now ...
i',m at beginner level of yii
how can i use it ... how enable drag&drop ? 

this is my code :
```php
<?php 
                        //$form->field($model, 'image')->textInput(['maxlength' => true]) 
                        echo ImageAttachmentWidget::widget(
                            [
                                'model' => $model,
                                'behaviorName' => 'coverBehavior',
                                'apiRoute' => 'news/imgAttachApi',
                            ]
                        )
                    ?>
```
how can i set the attribute of model ?

**Comment by zxbodya** [comment]
> how can i use it ?

You can show widget to attach new or replace existing image associated with object in you db..  Or you can use attached images whatever you need it.. 

>  can i set the attribute of model ?

What you mean?

> it cab use as input item?

It is not an input... It is standalone widget.

> what this code means ...?
```php
if ($model->getBehavior('coverBehavior')->hasImage()) {
    echo Html::img($model->getBehavior('coverBehavior')->getUrl('medium'));
}
```

It checks if there is image attached to model using coverBehavior, and if so - it renders image tag with 'medium' version of that image.

**Comment by mmbprog** [comment]
thank a lot ...
