### ISSUE TITLE
Upload gif images

### ISSUE THREAD

**Issue by tamvodopad** [zxbodya/yii2-image-attachment#7]
Hi, this is a best plugin for upload images.

But, have one small problem with upload gif animation images. 

I'm set 'extension' => 'gif', and if i'm uploaded gif image with animation this file saved without animations.

Sure, i'm understand resizing for this files not imposible, but original image save maybe possible.

**Comment by zxbodya** [comment]
Hi,

I am not sure about saving gif images, but likely imagine supports it: http://imagine.readthedocs.org/en/latest/usage/layers.html#animated-gif-frame-manipulation

Also there is an option to return save options for an image version(just updated example in readme)

```PHP
return [
    $img->copy()->resize($dstSize),
    ['jpeg_quality' => 80], // options used when saving image (Imagine::save)
];
```

As I understood to correctly save gif images - you need just add option `'flatten' => false`, and Imagine will preserve layers while saving.

**Comment by tamvodopad** [comment]
Thank you. 

Resize rules for animated gif not worked, because in Imagine documentation we will see:
http://imagine.readthedocs.org/en/latest/usage/layers.html#animated-gif-frame-manipulation

````php
<?php
$image = $imagine->open('cats.gif');

$image->layers()->coalesce();
foreach ($image->layers() as $frame) {
    $frame->resize(new Box(100, 100));
}

$image->save('resized-cats.gif', array('animated' => true));
````

If we manipulate with animated gif we will be manipulate with all frames.

--

Also, i.m redeclare rule for original image(image without manipulate):

````php
'versions' => [
                    'original' => function ($img) {
                        /** @var Imagine\Image\ImageInterface $img */
                        return [
                            $img,
                            [
                                'flatten' => false
                            ],
                        ];
                    }
                ]
````

and on this way on the output i see static gif without animate, this problem with Gdlib used by default in Yii2 Imagine. I'm send pull request to you with new option for configure Image library for Imagine.

**Comment by tamvodopad** [comment]
Worked example for correct saving animated gifs. Used #8 pull request modification

```php
'coverBehavior' => [
                'class' => ImageAttachmentBehavior::className(),
                // type name for model
                'type' => 'post',
                // image dimmentions for preview in widget
                'previewHeight' => 200,
                'previewWidth' => 300,
                'driver' => 'imagick',
                // extension for images saving
                'extension' => 'gif',
                // path to location where to save images
                'directory' => Yii::getAlias('@webroot') . '/images/works/cover',
                'url' => Yii::getAlias('@web') . '/images/works/cover',
                // additional image versions
                'versions' => [
                    'original' => function ($img) {
                        /** @var Imagine\Image\ImageInterface $img */
                        return [
                            $img,
                            [
                                'flatten' => false
                            ],
                        ];
                    }
                ]
            ],
```

**Comment by tamvodopad** [comment]
I'm resolve my problem with declare in  app/config/bootstrap.php:

````php

\yii\imagine\Image::$driver = 'imagick';
```

it's the better way for this.


Last problem that we have, it's problem with resize animate gif images. 

example code for resize animated gifs: http://imagine.readthedocs.org/en/latest/usage/layers.html#animated-gif-frame-manipulation
