### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException Class 'frontend\controllers\ImageAttachmentAction' not found

### ISSUE THREAD

**Issue by diego-betto** [zxbodya/yii2-image-attachment#9]
Hi, 

trying to use your extension with advanced template.

Added code in model, controller and view (_form) but this is the output: 
 PHP Fatal Error – yii\base\ErrorException
Class 'frontend\controllers\ImageAttachmentAction' not found

Any clue?

**Comment by zxbodya** [comment]
Hi,

do you have line `use zxbodya\yii2\imageAttachment\ImageAttachmentAction;` in you controller?

**Comment by diego-betto** [comment]
Added, now

Invalid Parameter – yii\base\InvalidParamException
common\models\Elemento has no relation named "image".

Can you explain me if i need to create a table or run migrations or where images data is stored?

Thank you

**Comment by diego-betto** [comment]
Ok solved, my fault with another extension. Thank you anyway :+1:

**Comment by zxbodya** [comment]
> Can you explain me if i need to create a table or run migrations or where images data is stored?
You do not need any extra fields in model to use it... Images are saved using primary key from your active record.
